//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crtCategory
    {
        public crtCategory()
        {
            this.crtCertificates = new HashSet<crtCertificate>();
        }
    
        public byte categoryID { get; set; }
        public string description { get; set; }
        public string categoryName { get; set; }
    
        public virtual ICollection<crtCertificate> crtCertificates { get; set; }
    }
}
