//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eveIcon
    {
        public eveIcon()
        {
            this.invMarketGroups = new HashSet<invMarketGroup>();
        }
    
        public int iconID { get; set; }
        public string iconFile { get; set; }
        public string description { get; set; }
    
        public virtual eveIcon eveIcons1 { get; set; }
        public virtual eveIcon eveIcon1 { get; set; }
        public virtual ICollection<invMarketGroup> invMarketGroups { get; set; }
    }
}
