//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eveUnit
    {
        public eveUnit()
        {
            this.dgmAttributeTypes = new HashSet<dgmAttributeType>();
        }
    
        public byte unitID { get; set; }
        public string unitName { get; set; }
        public string displayName { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<dgmAttributeType> dgmAttributeTypes { get; set; }
    }
}
