//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invTypeMaterial
    {
        public int typeID { get; set; }
        public int materialTypeID { get; set; }
        public int quantity { get; set; }
    
        public virtual invType invType { get; set; }
        public virtual invType invType1 { get; set; }
    }
}
