//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapSolarSystem
    {
        public mapSolarSystem()
        {
            this.chrFactions = new HashSet<chrFaction>();
            this.crpNPCCorporations = new HashSet<crpNPCCorporation>();
            this.mapDenormalizes = new HashSet<mapDenormalize>();
            this.mapLandmarks = new HashSet<mapLandmark>();
            this.mapSolarSystemJumps = new HashSet<mapSolarSystemJump>();
            this.mapSolarSystemJumps1 = new HashSet<mapSolarSystemJump>();
            this.ramAssemblyLineStations = new HashSet<ramAssemblyLineStation>();
            this.staStations = new HashSet<staStation>();
        }
    
        public Nullable<int> regionID { get; set; }
        public Nullable<int> constellationID { get; set; }
        public int solarSystemID { get; set; }
        public string solarSystemName { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> z { get; set; }
        public Nullable<double> xMin { get; set; }
        public Nullable<double> xMax { get; set; }
        public Nullable<double> yMin { get; set; }
        public Nullable<double> yMax { get; set; }
        public Nullable<double> zMin { get; set; }
        public Nullable<double> zMax { get; set; }
        public Nullable<double> luminosity { get; set; }
        public Nullable<bool> border { get; set; }
        public Nullable<bool> fringe { get; set; }
        public Nullable<bool> corridor { get; set; }
        public Nullable<bool> hub { get; set; }
        public Nullable<bool> international { get; set; }
        public Nullable<bool> regional { get; set; }
        public Nullable<bool> constellation { get; set; }
        public Nullable<double> security { get; set; }
        public Nullable<int> factionID { get; set; }
        public Nullable<double> radius { get; set; }
        public Nullable<int> sunTypeID { get; set; }
        public string securityClass { get; set; }
    
        public virtual ICollection<chrFaction> chrFactions { get; set; }
        public virtual chrFaction chrFaction { get; set; }
        public virtual ICollection<crpNPCCorporation> crpNPCCorporations { get; set; }
        public virtual invType invType { get; set; }
        public virtual mapConstellation mapConstellation { get; set; }
        public virtual ICollection<mapDenormalize> mapDenormalizes { get; set; }
        public virtual ICollection<mapLandmark> mapLandmarks { get; set; }
        public virtual mapRegion mapRegion { get; set; }
        public virtual ICollection<mapSolarSystemJump> mapSolarSystemJumps { get; set; }
        public virtual ICollection<mapSolarSystemJump> mapSolarSystemJumps1 { get; set; }
        public virtual ICollection<ramAssemblyLineStation> ramAssemblyLineStations { get; set; }
        public virtual ICollection<staStation> staStations { get; set; }
    }
}
