//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class chrFaction
    {
        public chrFaction()
        {
            this.invContrabandTypes = new HashSet<invContrabandType>();
            this.invControlTowerResources = new HashSet<invControlTowerResource>();
            this.mapConstellations = new HashSet<mapConstellation>();
            this.mapRegions = new HashSet<mapRegion>();
            this.mapSolarSystems = new HashSet<mapSolarSystem>();
        }
    
        public int factionID { get; set; }
        public string factionName { get; set; }
        public string description { get; set; }
        public Nullable<int> raceIDs { get; set; }
        public Nullable<int> solarSystemID { get; set; }
        public Nullable<int> corporationID { get; set; }
        public Nullable<double> sizeFactor { get; set; }
        public Nullable<short> stationCount { get; set; }
        public Nullable<short> stationSystemCount { get; set; }
        public Nullable<int> militiaCorporationID { get; set; }
        public Nullable<int> iconID { get; set; }
    
        public virtual crpNPCCorporation crpNPCCorporation { get; set; }
        public virtual crpNPCCorporation crpNPCCorporation1 { get; set; }
        public virtual mapSolarSystem mapSolarSystem { get; set; }
        public virtual ICollection<invContrabandType> invContrabandTypes { get; set; }
        public virtual ICollection<invControlTowerResource> invControlTowerResources { get; set; }
        public virtual ICollection<mapConstellation> mapConstellations { get; set; }
        public virtual ICollection<mapRegion> mapRegions { get; set; }
        public virtual ICollection<mapSolarSystem> mapSolarSystems { get; set; }
    }
}
