//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class crpNPCDivision
    {
        public crpNPCDivision()
        {
            this.agtAgents = new HashSet<agtAgent>();
            this.crpNPCCorporationDivisions = new HashSet<crpNPCCorporationDivision>();
        }
    
        public byte divisionID { get; set; }
        public string divisionName { get; set; }
        public string description { get; set; }
        public string leaderType { get; set; }
    
        public virtual ICollection<agtAgent> agtAgents { get; set; }
        public virtual ICollection<crpNPCCorporationDivision> crpNPCCorporationDivisions { get; set; }
    }
}
