//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class invGroup
    {
        public invGroup()
        {
            this.invTypes = new HashSet<invType>();
            this.invUniqueNames = new HashSet<invUniqueName>();
            this.mapDenormalizes = new HashSet<mapDenormalize>();
            this.ramAssemblyLineTypeDetailPerGroups = new HashSet<ramAssemblyLineTypeDetailPerGroup>();
        }
    
        public int groupID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string groupName { get; set; }
        public string description { get; set; }
        public Nullable<int> iconID { get; set; }
        public Nullable<bool> useBasePrice { get; set; }
        public Nullable<bool> allowManufacture { get; set; }
        public Nullable<bool> allowRecycler { get; set; }
        public Nullable<bool> anchored { get; set; }
        public Nullable<bool> anchorable { get; set; }
        public Nullable<bool> fittableNonSingleton { get; set; }
        public Nullable<bool> published { get; set; }
    
        public virtual invCategory invCategory { get; set; }
        public virtual ICollection<invType> invTypes { get; set; }
        public virtual ICollection<invUniqueName> invUniqueNames { get; set; }
        public virtual ICollection<mapDenormalize> mapDenormalizes { get; set; }
        public virtual ICollection<ramAssemblyLineTypeDetailPerGroup> ramAssemblyLineTypeDetailPerGroups { get; set; }
    }
}
