//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class invMarketGroup
    {
        public invMarketGroup()
        {
            this.invMarketGroups1 = new HashSet<invMarketGroup>();
            this.invTypes = new HashSet<invType>();
        }
    
        public int marketGroupID { get; set; }
        public Nullable<int> parentGroupID { get; set; }
        public string marketGroupName { get; set; }
        public string description { get; set; }
        public Nullable<int> iconID { get; set; }
        public Nullable<bool> hasTypes { get; set; }
    
        public virtual ICollection<invMarketGroup> invMarketGroups1 { get; set; }
        public virtual invMarketGroup invMarketGroup1 { get; set; }
        public virtual ICollection<invType> invTypes { get; set; }
    }
}
