//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveFirstMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class staService
    {
        public staService()
        {
            this.staOperations = new HashSet<staOperation>();
        }
    
        public int serviceID { get; set; }
        public string serviceName { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<staOperation> staOperations { get; set; }
    }
}
