//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class agtAgentType
    {
        public agtAgentType()
        {
            this.agtAgents = new HashSet<agtAgent>();
        }
    
        public int agentTypeID { get; set; }
        public string agentType { get; set; }
    
        public virtual ICollection<agtAgent> agtAgents { get; set; }
    }
}
