//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class crtCertificate
    {
        public crtCertificate()
        {
            this.crtRecommendations = new HashSet<crtRecommendation>();
            this.crtRelationships = new HashSet<crtRelationship>();
        }
    
        public int certificateID { get; set; }
        public Nullable<byte> categoryID { get; set; }
        public Nullable<int> classID { get; set; }
        public Nullable<byte> grade { get; set; }
        public Nullable<int> corpID { get; set; }
        public Nullable<int> iconID { get; set; }
        public string description { get; set; }
    
        public virtual crpNPCCorporation crpNPCCorporation { get; set; }
        public virtual crtCategory crtCategory { get; set; }
        public virtual crtClass crtClass { get; set; }
        public virtual ICollection<crtRecommendation> crtRecommendations { get; set; }
        public virtual ICollection<crtRelationship> crtRelationships { get; set; }
    }
}
