//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invMetaGroup
    {
        public invMetaGroup()
        {
            this.invMetaTypes = new HashSet<invMetaType>();
        }
    
        public short metaGroupID { get; set; }
        public string metaGroupName { get; set; }
        public string description { get; set; }
        public Nullable<int> iconID { get; set; }
    
        public virtual ICollection<invMetaType> invMetaTypes { get; set; }
    }
}
