//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class invMetaType
    {
        public int typeID { get; set; }
        public Nullable<int> parentTypeID { get; set; }
        public Nullable<short> metaGroupID { get; set; }
    
        public virtual invMetaGroup invMetaGroup { get; set; }
        public virtual invType invType { get; set; }
        public virtual invType invType1 { get; set; }
    }
}
